### ISSUE TITLE
panic: runtime error: index out of range at class_parser.go:196

### ISSUE THREAD

**Issue by Justin-W** [jfeliu007/goplantuml#64]
Certain projects cause goplantuml to crash with the following error:

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/jfeliu007/goplantuml/parser.(*ClassParser).handleGenDecl(0xc00004c140, 0xc00004ce80)
        /Users/justinw/go/src/github.com/jfeliu007/goplantuml/parser/class_parser.go:196 +0x13f3
github.com/jfeliu007/goplantuml/parser.(*ClassParser).parseFileDeclarations(0xc00004c140, 0x1133f40, 0xc00004ce80)
        /Users/justinw/go/src/github.com/jfeliu007/goplantuml/parser/class_parser.go:162 +0x81
github.com/jfeliu007/goplantuml/parser.(*ClassParser).parsePackage(0xc00004c140, 0x11331c0, 0xc000011590)
        /Users/justinw/go/src/github.com/jfeliu007/goplantuml/parser/class_parser.go:132 +0x207
github.com/jfeliu007/goplantuml/parser.(*ClassParser).parseDirectory(0xc00004c140, 0xc0000b8f00, 0x47, 0x47, 0x120e380)
        /Users/justinw/go/src/github.com/jfeliu007/goplantuml/parser/class_parser.go:153 +0xfa
github.com/jfeliu007/goplantuml/parser.NewClassDiagram.func1(0xc0000b8f00, 0x47, 0x1134cc0, 0xc00010dba0, 0x0, 0x0, 0x0, 0xc000125ab0)
        /Users/justinw/go/src/github.com/jfeliu007/goplantuml/parser/class_parser.go:89 +0x105
path/filepath.walk(0xc0000b8f00, 0x47, 0x1134cc0, 0xc00010dba0, 0xc00000c060, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:362 +0xe3
path/filepath.walk(0xc0000bc3c0, 0x40, 0x1134cc0, 0xc00010dad0, 0xc00000c060, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:382 +0x300
path/filepath.walk(0xc00001a180, 0x3c, 0x1134cc0, 0xc0000925b0, 0xc00000c060, 0x0, 0x20)
        /usr/local/go/src/path/filepath/path.go:382 +0x300
path/filepath.Walk(0xc00001a180, 0x3c, 0xc00000c060, 0x10a1d28, 0x0)
        /usr/local/go/src/path/filepath/path.go:404 +0xff
github.com/jfeliu007/goplantuml/parser.NewClassDiagram(0xc0000420c0, 0x1, 0x1, 0x120daa0, 0x0, 0x0, 0x1, 0xc0000420b0, 0xc00007ef20, 0x1010be4)
        /Users/justinw/go/src/github.com/jfeliu007/goplantuml/parser/class_parser.go:78 +0x424
main.main()
        /Users/justinw/go/src/github.com/jfeliu007/goplantuml/cmd/goplantuml/main.go:34 +0x228
```

**Comment by jfeliu007** [comment]
Interesting that's a type of declaration I have not handled yet. I can fix this issue by not assuming the Specs are going to be there. I need to see what declaration is doing that.

**Comment by Justin-W** [comment]
Verified fixed with latest master. All of the projects which were previously crashing no longer crash. Thanks!
